[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

## Calculation Contexts
# Destroying calculation on scoring_hand cards
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if destroyed then '''
match_indent = true
position = "before"
payload = '''
local destroyed_calc = eval_card(G.hand.cards[1], {destroying_card = G.hand.cards[1], full_hand = G.hand.cards})
if next(destroyed_calc) == 'destroyed' then destroyed = destroyed_calc end
'''


## G.FUNCS.evaluate_play()

 # Handle repetitions from playing cards
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
if next(eval) then
    for h = 1, eval.seals.repetitions do
        reps[#reps+1] = eval
    end
end
'''
position = 'at'
match_indent = true
payload = '''
for key, value in pairs(eval) do
    if value.repetitions then
        for h=1, value.repetitions do
            reps[#reps+1] = {key = value}
        end
    end
end
'''
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
if next(eval) and (next(effects[1]) or #effects > 1) then 
    for h  = 1, eval.seals.repetitions do
        reps[#reps+1] = eval
    end
end
'''
position = 'at'
match_indent = true
payload = '''
for key, value in pairs(eval) do
    if value.repetitions then
        for h=1, value.repetitions do
            reps[#reps+1] = {key = value}
        end
    end
end
'''

# Handle retrigger messages
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''card_eval_status_text((reps[j].jokers or reps[j].seals).card, 'jokers', nil, nil, nil, (reps[j].jokers or reps[j].seals))'''
position = 'at'
match_indent = true
payload = '''
local _, eff = next(reps[j])
card_eval_status_text(eff.card, 'jokers', nil, nil, nil, eff)'''

## eval_card()
# built in config values
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''local chips = card:get_chip_bonus()
if chips > 0 then 
    ret.chips = chips
end

local mult = card:get_chip_mult()
if mult > 0 then 
    ret.mult = mult
end

local x_mult = card:get_chip_x_mult(context)
if x_mult > 0 then 
    ret.x_mult = x_mult
end

local p_dollars = card:get_p_dollars()
if p_dollars > 0 then 
    ret.p_dollars = p_dollars
end'''
match_indent = true
position = "at"
payload = """
ret.card = {card = card}
local chips = card:get_chip_bonus()
if chips > 0 then 
    ret.card.chips = chips
end

local mult = card:get_chip_mult()
if mult > 0 then 
    ret.card.mult = mult
end

local x_mult = card:get_chip_x_mult(context)
if x_mult > 0 then 
    ret.card.x_mult = x_mult
end

local p_dollars = card:get_p_dollars()
if p_dollars > 0 then 
    ret.card.p_dollars = p_dollars
end
"""
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
local h_mult = card:get_chip_h_mult()
if h_mult > 0 then 
    ret.h_mult = h_mult
end

local h_x_mult = card:get_chip_h_x_mult()
if h_x_mult > 0 then 
    ret.x_mult = h_x_mult
end
'''
match_indent = true
position = "at"
payload = """
ret.card = {card = card}
local h_mult = card:get_chip_h_mult()
if h_mult > 0 then 
    ret.card.h_mult = h_mult
end

local h_x_mult = card:get_chip_h_x_mult()
if h_x_mult > 0 then 
    ret.card.x_mult = h_x_mult
end
"""
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local seals = card:calculate_seal(context)"
match_indent = true
position = "before"
payload = """
local enhancement = card:calculate_enhancement(context)
if enhancement then
    ret.enhancement = enhancement
end
for k,v in pairs(SMODS.Stickers) do
    local sticker = card:calculate_sticker(context, k)
    if sticker then
        ret[v] = sticker
    end
end
"""
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if context.cardarea == G.jokers or context.card == G.consumeables then"
match_indent = true
position = "before"
payload = """
local enhancement = card:calculate_enhancement(context)
if enhancement then
    ret.enhancement = enhancement
end
local seals = not card.ability.extra_enhancement and card:calculate_seal(context)
if seals then
    ret.seals = seals
end"""

[[patches]]
[patches.regex]
target = 'functions/common_events.lua'
position = 'after'
pattern = '( ){4}if context\.cardarea == G\.jokers or context\.card == G\.consumeables then(\n.*)*?\n( ){4}end'
payload = '''
    for k,v in pairs(SMODS.Stickers) do
        local sticker = card:calculate_sticker(context, k)
        if sticker then
            ret[v] = sticker
        end
    end
'''

# G.FUNCS.evaluate_play()
# handle scoring
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''--If x_mult added, do mult add event and mult the mult to the total'''
match_indent = true
position = "before"
payload = '''
for key, effect in pairs(effects[ii]) do
    if type(effect) == 'table' then
        SMODS.calculate_effect(effect, scoring_hand[i], percent)
    end
end
'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''j = j +1'''
match_indent = true
position = "at"
payload = '''
j = j + (next(effects[1]) and 1 or #reps)
'''

# Joker repetition evaluation wrapper
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if next(eval) then 
    for h  = 1, eval.jokers.repetitions do
        reps[#reps+1] = eval
    end
end
'''
match_indent = true
position = "at"
payload = '''
for key, value in pairs(eval) do
    if value.repetitions then
        for h=1, value.repetitions do
            reps[#reps+1] = {key = value}
        end
    end
end
'''
# Joker repetition evaluation wrapper
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if next(eval) and eval.jokers then 
    for h = 1, eval.jokers.repetitions do
        reps[#reps+1] = eval
    end
end
'''
match_indent = true
position = "at"
payload = '''
for key, value in pairs(eval) do
    if value.repetitions then
        for h=1, value.repetitions do
            reps[#reps+1] = {key = value}
        end
    end
end
'''


## Remove base game calculations
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
--If chips added, do chip add event and add the chips to the total
if effects[ii].chips then 
    if effects[ii].card then juice_card(effects[ii].card) end
    hand_chips = mod_chips(hand_chips + effects[ii].chips)
    update_hand_text({delay = 0}, {chips = hand_chips})
    card_eval_status_text(scoring_hand[i], 'chips', effects[ii].chips, percent)
end

--If mult added, do mult add event and add the mult to the total
if effects[ii].mult then 
    if effects[ii].card then juice_card(effects[ii].card) end
    mult = mod_mult(mult + effects[ii].mult)
    update_hand_text({delay = 0}, {mult = mult})
    card_eval_status_text(scoring_hand[i], 'mult', effects[ii].mult, percent)
end

--If play dollars added, add dollars to total
if effects[ii].p_dollars then 
    if effects[ii].card then juice_card(effects[ii].card) end
    ease_dollars(effects[ii].p_dollars)
    card_eval_status_text(scoring_hand[i], 'dollars', effects[ii].p_dollars, percent)
end

--If dollars added, add dollars to total
if effects[ii].dollars then 
    if effects[ii].card then juice_card(effects[ii].card) end
    ease_dollars(effects[ii].dollars)
    card_eval_status_text(scoring_hand[i], 'dollars', effects[ii].dollars, percent)
end
'''
match_indent = true
position = "at"
payload = '''
-- Base game calculation removed
'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
--if this effect came from a joker
if effects[ii].card then
    mod_percent = true
    G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = (function() effects[ii].card:juice_up(0.7);return true end)
    }))
end

--If hold mult added, do hold mult add event and add the mult to the total

--If dollars added, add dollars to total
if effects[ii].dollars then 
    ease_dollars(effects[ii].dollars)
    card_eval_status_text(G.hand.cards[i], 'dollars', effects[ii].dollars, percent)
end

if effects[ii].h_mult then
    mod_percent = true
    mult = mod_mult(mult + effects[ii].h_mult)
    update_hand_text({delay = 0}, {mult = mult})
    card_eval_status_text(G.hand.cards[i], 'h_mult', effects[ii].h_mult, percent)
end

if effects[ii].x_mult then
    mod_percent = true
    mult = mod_mult(mult*effects[ii].x_mult)
    update_hand_text({delay = 0}, {mult = mult})
    card_eval_status_text(G.hand.cards[i], 'x_mult', effects[ii].x_mult, percent)
end

if effects[ii].message then
    mod_percent = true
    update_hand_text({delay = 0}, {mult = mult})
    card_eval_status_text(G.hand.cards[i], 'extra', nil, percent, nil, effects[ii])
end
'''
match_indent = true
position = "at"
payload = '''
-- Base game calculation removed 2
for key, effect in pairs(effects[ii]) do
    if type(effect) == 'table' then
        SMODS.calculate_effect(effect, G.hand.cards[i], percent)
    end
end
'''