[manifest]
version = "1.0.0"
dump_lua = true
priority = 69

#
# Use number_format for...
#

# DynaText

[[patches]] 
[patches.regex]
target = "engine/text.lua"
pattern = 'tostring\((?<param>v\.ref_table and v\.ref_table\[v\.ref_value\] or v\.string)\)'
position = "at"
payload = "format_ui_value($param)"

# Cash Out

[[patches]] 
[patches.regex]
target = "functions/common_events.lua"
pattern = '''
localize\('\$'\)\.\.config\.dollars'''
position = "at"
payload = "localize('$')..format_ui_value(config.dollars)"

# End of round money

[[patches]]
[patches.regex]
target = "functions/common_events.lua"
pattern = '''
localize\('\$'\)\.\.num_dollars\}'''
position = "at"
payload = "localize('$')..format_ui_value(num_dollars)}"

# Tooltip numbers

[[patches]] 
[patches.regex]
target = "functions/misc_functions.lua"
pattern = '(?<param>args\.vars\[tonumber\(subpart\[1\]\)\])'
position = "at"
payload = 'format_ui_value($param)'

# Poker Hand chips

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "{n=G.UIT.T, config={text = G.GAME.hands[handname].chips, scale = 0.45, colour = G.C.UI.TEXT_LIGHT}},"
position = "at"
payload = "{n=G.UIT.T, config={text = number_format(G.GAME.hands[handname].chips, 1000000), scale = 0.45, colour = G.C.UI.TEXT_LIGHT}},"
match_indent = true

# Poker Hand mult

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "{n=G.UIT.T, config={text = G.GAME.hands[handname].mult, scale = 0.45, colour = G.C.UI.TEXT_LIGHT}}"
position = "at"
payload = "{n=G.UIT.T, config={text = number_format(G.GAME.hands[handname].mult, 1000000), scale = 0.45, colour = G.C.UI.TEXT_LIGHT}}"
match_indent = true

# Continue Run - Money

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = 'tostring\(saved_game\.GAME\.dollars\)'
position = "at"
payload = "format_ui_value(saved_game.GAME.dollars)"

# Continue Run - Best Hand - bigger size

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = 'scale_number\(saved_game\.GAME\.round_scores\.hand\.amt\, 0\.8\*scale\)'
position = "at"
payload = "score_number_scale(scale*1.1, saved_game.GAME.round_scores.hand.amt)"


#
# Custom sci notation switch point
#

# number_format

[[patches]] 
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = 'function number_format(num)'
position = "at"
payload = 'function number_format(num, e_switch_point)'
match_indent = true

# score_number_scale

[[patches]] 
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = 'function score_number_scale(scale, amt)'
position = "at"
payload = 'function score_number_scale(scale, amt, e_switch_point)'
match_indent = true

# Check if custom switch point is specified

[[patches]] 
[patches.regex]
target = "functions/misc_functions.lua"
pattern = '>= G\.E_SWITCH_POINT'
position = "at"
payload = ">= (e_switch_point or G.E_SWITCH_POINT)"

