[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = "core/lua_reload.lua"
before = "main.lua"
name = "lua_reload"

[[patches]]
[patches.pattern]
target = 'main.lua'
pattern = "if (love.system.getOS() == 'OS X' ) and (jit.arch == 'arm64' or jit.arch == 'arm') then jit.off() end"
position = 'after'
match_indent = true
payload = '''
lua_reload = require('lua_reload')
lua_reload.Inject()
'''