name: Build-Windows


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false

      
    runs-on: windows-latest

    
    steps:
      # Check-out repository
      - uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt


      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests


      # Build python script into a stand-alone exe
      # - uses: jimkring/python-script-to-exe@v0.2.0
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: injector/steamodded_injector.py
          onefile: true
          standalone: true
          # access-token: ${{ secrets.NUITKA_COMMERCIAL_ACCESS_TOKEN }}
          # macos-create-app-bundle: ${{ runner.os == 'macOS' }}
          include-data-dir: |
            injector/core=core
            injector/debug=debug
            injector/loader=loader


      # Uploads artifacts
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Steamodded-Windows-${{github.run_id}}
          path: build/steamodded_injector.exe


#      - name: Generate Changelog
#        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt


#      - name: Check and Update Nightly Release
#        id: update_nightly
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          REPO_NAME: ${{ github.repository }}
#        run: |
#          echo "::set-output name=upload_url::$(python .github/scripts/update_nightly_release.py)"


      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@master
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          prerelease: true
          tag_name: Nightly-${{github.run_id}}
          name: Nightly-${{github.run_id}}
          token: ${{ secrets.GITHUB_TOKEN }}
          #body_path: ${{ github.workspace }}-CHANGELOG.txt
          #upload_url: ${{ steps.update_nightly.outputs.upload_url }}
          files: build/steamodded_injector.exe
          #asset_name: Steamodded-Windows-${{github.run_id}}.exe
          #asset_content_type: application/octet-stream
