name: Compile Python to EXE with Nuitka

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Nuitka and dependencies
      run: pip install -U nuitka==1.9.4 requests
    - name: Compile Python script to EXE
      run: python -m nuitka --assume-yes-for-downloads --standalone --onefile --follow-imports --include-package=socket --include-module=requests --include-module=urllib3 --include-data-dir=core=./core --include-data-dir=debug=./debug --include-data-dir=loader=./loader steamodded_injector.py
    - name: Upload EXE to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: steamodded_injector
        path: ./steamodded_injector.dist/steamodded_injector.exe
